
const TEST_RAW_S = [
    1.16e3, 1.31e3, 1.57e3, 1.76e3, 1.94e3,
    2.31e3, 2.57e3, 3.11e3, 3.38e3, 3.77e3,
    4.58e3, 5.06e3, 6.22e3, 7.51e3, 8.78e3,
    9.68e3, 1.10e4, 1.20e4, 1.27e4, 1.40e4,
    1.57e4, 1.62e4, 1.69e4, 1.77e4, 1.86e4,
    1.98e4, 2.12e4, 2.26e4, 2.36e4, 2.55e4,
    2.65e4, 2.82e4, 2.97e4, 3.12e4, 3.20e4,
    3.37e4, 3.41e4, 3.50e4, 3.64e4, 3.71e4,
    3.78e4, 3.83e4, 3.87e4
]
const TEST_S = [
    1.49e2, 2.99e2, 5.65e2, 7.57e2, 9.29e2,
    1.30e3, 1.56e3, 2.10e3, 2.37e3, 2.76e3,
    3.57e3, 4.05e3, 5.21e3, 6.51e3, 7.77e3,
    8.67e3, 9.95e3, 1.10e4, 1.17e4, 1.30e4,
    1.47e4, 1.52e4, 1.59e4, 1.67e4, 1.76e4,
    1.88e4, 2.02e4, 2.16e4, 2.26e4, 2.45e4,
    2.55e4, 2.72e4, 2.87e4, 3.02e4, 3.10e4,
    3.26e4, 3.31e4, 3.40e4, 3.53e4, 3.61e4,
    3.68e4, 3.73e4, 3.77e4
]
const TEST_RMS = [
    1.22e1, 1.63e1, 2.19e1, 2.52e1, 2.79e1,
    3.32e1, 3.65e1, 4.27e1, 4.57e1, 4.99e1,
    5.71e1, 6.14e1, 6.99e1, 7.84e1, 8.67e1,
    9.20e1, 9.88e1, 1.03e2, 1.08e2, 1.15e2,
    1.22e2, 1.26e2, 1.27e2, 1.31e2, 1.36e2,
    1.39e2, 1.44e2, 1.51e2, 1.55e2, 1.54e2,
    1.58e2, 1.63e2, 1.64e2, 1.64e2, 1.66e2,
    1.60e2, 1.59e2, 1.61e2, 1.51e2, 1.49e2,
    1.38e2, 1.30e2, 1.11e2
]

"""
    testdata()

Loads a tuple of the signal and total noise from the Appendix A table A.1 from Janesick (2007).[^1] This data is generated by a CMOS imager with V/e- nonlinearity. Data units are in DN.

# Examples

```jldoctest
julia> data = testdata();

julia> size(data.S)
43
```

[^1]: James R. Janesick, 2007, ["Photon Transfer"](https://www.spiedigitallibrary.org/ebooks/PM/Photon-Transfer/eISBN-9780819478382/10.1117/3.725073?SSO=1), SPIE
"""
testdata() = (S=TEST_S, total_noise=TEST_RMS, raw_S=TEST_RAW_S)
